-- Create courses table
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    students INT DEFAULT 0,
    attendance FLOAT DEFAULT 0,
    next_session TIMESTAMP WITH TIME ZONE,
    semester TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    description TEXT,
    schedule TEXT,
    location TEXT,
    start_date DATE,
    end_date DATE,
    instructor TEXT,
    credits INT DEFAULT 3,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
-- Create RLS policies
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
-- Allow read access for all authenticated users
CREATE POLICY "Allow read access for all authenticated users" ON courses FOR
SELECT TO authenticated USING (true);
-- Allow insert/update/delete for authenticated users
CREATE POLICY "Allow insert for authenticated users" ON courses FOR
INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow update for authenticated users" ON courses FOR
UPDATE TO authenticated USING (true);
CREATE POLICY "Allow delete for authenticated users" ON courses FOR DELETE TO authenticated USING (true);